# Generated by Django 2.0.3 on 2018-08-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equitstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(default='未填写', max_length=20, unique=True, verbose_name='姓名')),
                ('equit_permission', models.IntegerField(default=1, verbose_name='设备权限等级')),
                ('phone', models.CharField(default='未填写', max_length=20, verbose_name='联系方式')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('oper_sys', models.CharField(default='未填写', max_length=80, verbose_name='操作系统')),
                ('sys_prog', models.CharField(default='未填写', max_length=100, verbose_name='系统程序')),
                ('sw_ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='交换机IP地址或虚拟机物理主机地址')),
                ('act_date', models.DateField(blank=True, null=True, verbose_name='启用时间')),
                ('equit_name', models.CharField(default='未填写', max_length=60, verbose_name='设备名称')),
                ('cab_id', models.CharField(default='未填写', max_length=16, verbose_name='机架号')),
                ('staff_name', models.CharField(default='未填写', max_length=20, verbose_name='维护人员')),
                ('staff_phone', models.CharField(default='未填写', max_length=20, verbose_name='联系方式')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
