# Generated by Django 2.0.3 on 2018-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0002_auto_20180816_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitstaff',
            name='equit_permission',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='设备权限等级'),
        ),
    ]
