# Generated by Django 2.0.3 on 2018-08-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0005_auto_20180816_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='staff',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='equit.Equitstaff'),
        ),
        migrations.AlterField(
            model_name='info',
            name='staff_name',
            field=models.CharField(default='未认领', max_length=20, verbose_name='维护人员'),
        ),
    ]
