# Generated by Django 2.0.3 on 2018-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0006_auto_20180820_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='sw_ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='网关'),
        ),
    ]
