# Generated by Django 2.0.3 on 2018-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0007_auto_20180928_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='sw_port',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='交换机端口'),
        ),
        migrations.AlterField(
            model_name='info',
            name='sw_ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='交换机'),
        ),
    ]
