# Generated by Django 2.0.3 on 2018-11-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0008_auto_20181112_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.BooleanField(default=True, verbose_name='设备状态'),
        ),
    ]
