# Generated by Django 2.0.3 on 2018-11-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0009_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='deact_date',
            field=models.DateField(default='2099-12-31', verbose_name='停用时间'),
        ),
    ]
