# Generated by Django 2.0.3 on 2018-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0011_auto_20181123_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址'),
        ),
    ]
