# Generated by Django 2.0.3 on 2018-11-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0012_auto_20181128_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='act_date',
            field=models.DateField(default='2001-1-1', verbose_name='启用时间'),
        ),
    ]
