# Generated by Django 2.0.3 on 2018-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equit', '0013_auto_20181130_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='equit_name',
            field=models.CharField(max_length=90, verbose_name='设备名称'),
        ),
    ]
